version: 2

models:
  - name: taxis_ingest
    description: All green taxi data for 2014 where the trip started in UTC 2014
    columns:
      - name: vendor_id
        description: A code indicating the LPEP provider that provided the record. 1= Creative Mobile Technologies, LLC; 2= VeriFone Inc.
      - name: pickup_datetime
        description: The date and time when the meter was engaged
      - name: dropoff_datetime
        description: The date and time when the meter was disengaged
      - name: store_and_fwd_flag
        description: This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka 'store and forward,' because the vehicle did not have a connection to the server. Y= store and forward trip N= not a store and forward trip
      - name: rate_code
        description: The final rate code in effect at the end of the trip. 1= Standard rate 2=JFK 3=Newark 4=Nassau or Westchester 5=Negotiated fare 6=Group ride
      - name: passenger_count
        description: The number of passengers in the vehicle. This is a driver-entered value.
      - name: trip_distance
        description: The elapsed trip distance in miles reported by the taximeter.
      - name: fare_amount
        description: The time-and-distance fare calculated by the meter
      - name: extra
        description: Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges
      - name: mta_tax
        description: $0.50 MTA tax that is automatically triggered based on the metered rate in use
      - name: tip_amount
        description: Tip amount. This field is automatically populated for credit card tips. Cash tips are not included.
      - name: tolls_amount
        description: Total amount of all tolls paid in trip.
      - name: ehail_fee
      - name: airport_fee
      - name: total_amount
        description: The total amount charged to passengers. Does not include cash tips.
      - name: payment_type
        description: A numeric code signifying how the passenger paid for the trip. 1= Credit card 2= Cash 3= No charge 4= Dispute 5= Unknown 6= Voided trip
      - name: distance_between_service
      - name: time_between_service
      - name: trip_type
        description: A code indicating whether the trip was a street-hail or a dispatch that is automatically assigned based on the metered rate in use but can be altered by the driver. 1= Street-hail 2= Dispatch
      - name: imp_surcharge
        description: $0.30 improvement surcharge assessed on hailed trips at the flag drop. The improvement surcharge began being levied in 2015.
      - name: pickup_location_id
        description: TLC Taxi Zone in which the taximeter was engaged
      - name: dropoff_location_id
        description: TLC Taxi Zone in which the taximeter was disengaged
      - name: data_file_year
        description: Datafile timestamp year value
      - name: data_file_month
        description: Datafile timestamp month value
        
  - name: taxis_clean
    description: cleaned