version: 2

sources:
    - name: nyc_taxi
      description: public taxi data
      database: bigquery-public-data
      schema: new_york_taxi_trips
      tables:
          - name: tlc_green_trips_2014
            description: All green taxi data for 2014 where the trip started in UTC 2014.